#!/usr/bin/env bash
# macos-scripts/cleanup

# cleanup
#  Purge some caches and take out the trash

set -euo pipefail
# -e exit if any command returns non-zero status code
# -u prevent using undefined variables
# -o pipefail force pipelines to fail on first non-zero status code

IFS=$'\n\t'
# Set Internal Field Separator to newlines and tabs
# This makes bash consider newlines and tabs as separating words
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode/

### UTILITY FUNCTIONS ###
# check_developer_tools


function check_developer_tools {

  if ! xcode-select -p >/dev/null 2>&1; then 
    echo "[❌] Command line developer tools required"
    echo "[🍺] Install via: xcode-select --install"
    exit 1
  fi
}


### END UTILITY FUNCTIONS ###


function clean_xcode {
  # Delete old iOS simulators
  
  if check_developer_tools; then
    echo "[🗑] Deleting old Xcode iOS Simulators"
    
    xcrun simctl delete unavailable
  fi
}


function clean_brew {
  # Remove outdated downloads for formulae and casks, 
  # and remove old versions of installed formulae.
  # Scrub the cache of the latest versions

  
  if [ -x "$(command -v brew)" ]; then
    echo "[🗑] Cleaning Brew"

    brew cleanup -s
    # Remove cache for installed formula and cask 
    rm -rf "$(brew --cache)"
  fi
}


function clean_ruby {
  # Remove old versions of gems 
  # that are not required to meet a dependency.

  if [ -x "/usr/local/opt/ruby/bin/gem" ]; then
    echo "[🗑] Cleaning Ruby Gems"
    
    /usr/local/opt/ruby/bin/gem cleanup >/dev/null 2>&1
  fi
}


function empty_trash {

  echo "[🗑] Emptying Trash"

  rm -rf "${HOME:?}/.Trash/"*
}


function main {

  clean_brew
  clean_ruby
  empty_trash
}

main "$@"
